development:
  adapter: postgresql
  database: my_database_development
  encoding: unicode
  username: myhandbo
  password: 123456
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  encoding: unicode
  username: myhandbo
  password: 123456
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000