development:
  adapter: postgresql
  database: my_database_development
  username: myhandbo
  password: 123456
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_test
  username: myhandbo
  password: 123456
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: myhandbo
  password: 123456
  database: my_database_production
  pool: 5
  timeout: 5000